
name: Bot Push

on:
  pull_request:
    branches: [ "main" ]
    paths:
      - 'backend/**'

jobs:
  increment:
    runs-on: ubuntu-latest
    if: github.actor == 'chavna-actions-bot'
    steps:
      - name: Test
        run: echo ${{ github.actor }}
      - name: Trigger Build
        run: echo "Triggering build..."