
name: Deployment Workflow

on:
  workflow_run:
    workflows: [Backend Workflow, Frontend Workflow]
    types:
      - completed

env:
  GH_TOKEN: ${{ github.token }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions: write-all

    steps:
    - uses: actions/checkout@v4
    - uses: actions/download-artifact@v4.1.7
    - name: Get Backend Run Id
      run: gh run list --workflow "Backend Workflow" --status success --json databaseId --jq '.[0].databaseId'
    - name: Get Frontend Run Id
      run: gh run list --workflow "Frontend Workflow" --status success --json databaseId --jq '.[0].databaseId'
    # - name: Configure AWS Credentials
    #   uses: aws-actions/configure-aws-credentials@v4
    #   with:
    #     aws-region: us-east-1
    #     aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
    #     aws-secret-access-key: ${{ secrets.AWS_ACCESS_KEY_SECRET }}
    # - name: Deploy to AWS
    #   run: |
    #     aws s3 cp "deploy-files/${{github.run_id}}.jar" s3://elasticbeanstalk-us-east-1-${{ secrets.AWS_ACCOUNT_ID }}/artifact/java-app/
    #     aws elasticbeanstalk create-application-version --application-name $ELASTIC_BEANSTALK_NAME --version-label ${{github.run_id}} --description ${{github.run_id}} --source-bundle S3Bucket="elasticbeanstalk-us-east-1-${{ secrets.AWS_ACCOUNT_ID }}",S3Key="artifact/java-app/${{github.run_id}}.jar"
    #     aws elasticbeanstalk update-environment --application-name $ELASTIC_BEANSTALK_NAME --environment-name $ELASTIC_BEANSTALK_ENV_NAME --version-label ${{github.run_id}}
    #     aws elasticbeanstalk wait environment-updated --application-name $ELASTIC_BEANSTALK_NAME --environment-name $ELASTIC_BEANSTALK_ENV_NAME
    # - name: Create Release
    #   id: create_release
    #   uses: actions/create-release@v1
    #   env:
    #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    #   with:
    #     tag_name: ${{github.run_id}}
    #     release_name: Release ${{github.run_id}}
    #     draft: false
    #     prerelease: false
    # - name: Upload Release Asset
    #   id: upload-release-asset 
    #   uses: actions/upload-release-asset@v1
    #   env:
    #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    #   with:
    #     upload_url: ${{ steps.create_release.outputs.upload_url }} # This pulls from the CREATE RELEASE step above, referencing it's ID to get its outputs object, which include a `upload_url`. See this blog post for more info: https://jasonet.co/posts/new-features-of-github-actions/#passing-data-to-future-steps 
    #     asset_path: deploy-files/${{github.run_id}}.jar
    #     asset_name: server.jar
    #     asset_content_type: application/java-archive
